### PR TITLE
Simple process Health checker introduced

### PR DESCRIPTION
**Pull request by yashodhank**

### CODE REVIEW

**Comment by humenius** [comment]
Hi! 

Thank you for your contribution. 👍 
At first glance, looks fine for me. I test it as soon as possible.

**Comment by humenius** [comment]
I noticed there is a `HEALTHCHECK` instruction for Dockerfiles. Is it better to use them instead?

**Comment by yashodhank** [comment]
Totally, works for me..

There can only be one `HEALTHCHECK` instruction in a Dockerfile. If you list more than one then only the last HEALTHCHECK will take effect.

**Comment by humenius** [comment]
Well, this health check might be the only one for now which means maybe it’s better idea to implement in the Dockerfiles instead of `docker-compose.yml`. Then you don’t have to add health check explicitly. In Dockerfile, it comes out of the box. 

Unless adding it only to `docker-compose.yml` is better – in the case when we add multiple health checks?

**Comment by yashodhank** [comment]
First approach would be fine by me, I am totally OK with whatever approach you may decide to go ahead with.. :)
Thanks

**Comment by humenius** [comment]
I moved the healthcheck script into a `bin/` folder and added it to the `Dockerfile`. Might move `run.sh` later on. 

I merge this one. Thank you for your contribution. :)

**Review by humenius — APPROVED** [review]

**Pull request merged**
