### PR TITLE
Add support for arm64/armhf builds

### PR DESCRIPTION
**Pull request by rfgamaral**
This change adds support for multi-arch images (arm64/armhf) which includes devices like a Raspberry Pi. I've also changed the base build image to `ldez/traefik-certs-dumper` instead of `docker` which simplifies the image and makes it smaller.

This won't do anything by itself, you'll need to update your build process to build each `Dockerfile` individually, push them to Docker Hub individually and then create and push a manifest file with the proper tags.

I personally use GitHub Actions for all of this and although I don't have the most simplified process, here's an example for you:

- https://github.com/rfgamaral/docker-gphotos-uploader/tree/master/.github

I've also did a similar thing to my fork just for testing purposes:

- https://github.com/rfgamaral/traefik-certs-dumper/tree/preview/.github
- https://hub.docker.com/repository/docker/rfgamaral/traefik-certs-dumper

### CODE REVIEW

**Comment by humenius** [comment]
Hi,

the current image uses Docker due to restart functionality. However, #8 addresses this issue indirectly which means it's not a bad idea to use `ldez/traefik-certs-dumper` as a base image. It would have been fine too to add multi-arch images as well.

I quickly scanned over it and it looks fine to me, but we may
- have to update `run.sh` to check the availability of Docker inside the container
- think about how to name the tags

About #8: Maybe we can consider combining issues together

**Comment by rfgamaral** [comment]
> the current image uses Docker due to restart functionality.

I wasn't aware of this, sorry... I guess #8 needs to be done first. Or maybe I shouldn't have made two changes in one PR, sorry about that.

**Comment by humenius** [comment]
Ah, don’t worry. :D

 

With your multi-arch suggestion, I guess it’s a good time now to start with #8 and maybe combine it with your PR or something. I start working on it.

 

Von: Ricardo Amaral <notifications@github.com> 
Gesendet: Samstag, 29. August 2020 12:28
An: humenius/traefik-certs-dumper <traefik-certs-dumper@noreply.github.com>
Cc: humenius <contact@humenius.me>; Comment <comment@noreply.github.com>
Betreff: Re: [humenius/traefik-certs-dumper] Add support for arm64/armhf builds (#21)

 

the current image uses Docker due to restart functionality.

I wasn't aware of this, sorry... I guess #8 <https://github.com/humenius/traefik-certs-dumper/issues/8>  needs to be done first. Or maybe I shouldn't have made two changes in one PR, sorry about that.

**Comment by rfgamaral** [comment]
>     * have to update `run.sh` to check the availability of Docker inside the container

What do you mean? I don't think you need to do much...

>     * think about how to name the tags

My recommendation is to follow what I have done here: https://hub.docker.com/repository/docker/rfgamaral/traefik-certs-dumper/tags?page=1 (replace `preview` with `latest` or a version number).

**Comment by humenius** [comment]
> ```
> * have to update `run.sh` to check the availability of Docker inside the container
> ```

Yeah, I figured you can check if the `docker` command exists via `[ -x "$(command -v docker)" ]`

> > ```
> > * think about how to name the tags
> > ```
> 
> My recommendation is to follow what I have done here: https://hub.docker.com/repository/docker/rfgamaral/traefik-certs-dumper/tags?page=1 (replace `preview` with `latest` or a version number).

Yep, looks fine. Also, we can prepend the version number and omit it for latest releases.
I try to start working on it. 👍

**Comment by humenius** [comment]
Sorry that this took some time. I really like your suggestion of using GitHub Actions and how it works. Looks pretty neat. I cherry-picked your commit and modified it a little bit.

I also added the image variations `docker` and `alpine`. Best way to find out if the images work is to build them and check for errors. Maybe we can add another workflow or step for test-building the images.

**Comment by rfgamaral** [comment]
Looks good.

But I don't recommend custom actions like I originally did on my repo, makes it harder to maintain (although I haven't touched that code since I first added it). I believe there are third-party actions available in the marketplace that perhaps you could use to simplify the build process but I haven't personally looked much into that yet.

**Comment by humenius** [comment]
I probably have to merge this one as of [GitHub](https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets#using-encrypted-secrets-in-a-workflow), secrets cannot be passed to forked repositories.

**Comment by rfgamaral** [comment]
> 
> 
> I probably have to merge this one as of [GitHub](https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets#using-encrypted-secrets-in-a-workflow), secrets cannot be passed to forked repositories.

You can always merge it and give the finishing touches on the `develop` branch until it's ready to be merged to `master` :)

**Pull request merged**
