### PR TITLE
Ownership, permissions and container restart fix

### PR DESCRIPTION
**Pull request by pwatk**
I'm submitting these three commits for review.

1. Fix UID/GID changes only being applied to the first file encountered.
2. Give read permissions to OVERRIDE_GID for all files.
3. Fix containers being restarted on every run.

### CODE REVIEW

**Comment by humenius** [comment]
Looks pretty straight forward to me. I'll give it a shot as soon as I can. Thank you in advance. :)

**Comment by pwatk** [comment]
I only use one domain so when I said all files I meant cert.pem and key.pem. The command looks for any .pem files in the output directory though.

The issue I had was only cert.pem was having it’s ownership changed.

Given that cert.pem comes alphabetically  before key.pem I deduced that the find command was stopping after the first file it encountered.

Adding a while loop to the find command fixed this for me.

**Comment by pwatk** [comment]
Sorry I miss read your question.

I added `chmod g+r` to the find command so the group permission is changed to read at the same time as the files ownership.

Ultimately this means that key.pem allows read access to the `$OVERRIDE_GID` group as well as cert.pem.

**Comment by humenius** [comment]
> Sorry I miss read your question.
> 
> I added `chmod g+r` to the find command so the group permission is changed to read at the same time as the files ownership.
> 
> Ultimately this means that key.pem allows read access to the `$OVERRIDE_GID` group as well as cert.pem.



> I only use one domain so when I said all files I meant cert.pem and key.pem. The command looks for any .pem files in the output directory though.
> 
> The issue I had was only cert.pem was having it’s ownership changed.
> 
> Given that cert.pem comes alphabetically before key.pem I deduced that the find command was stopping after the first file it encountered.
> 
> Adding a while loop to the find command fixed this for me.

Ah, yeah. Makes sense now. 👍 
Well, as mentioned above, everything seemed to work fine. I'm merging the changes now and I'll create a new release later on.
Thank you for your contribution. :)

**Comment by pwatk** [comment]
Thank you.

**Pull request merged**
